### ISSUE TITLE
When extracting Fallout4 files I'm getting sizes that are too small

### ISSUE THREAD

**Issue by Niedzwiedzw** [Ryan-rsm-McKenzie/bsa-rs#2]
hey so the mismatch is pretty big, I'm thinking I might be handling compression incorrectly?

error:
```
2. when extracting from [/home/niedzwiedz/Games/modding/hoolamike/playground/downloads/Data_Fallout4 - Textures7.ba2] to [./TEMP_BSA_FILES/546ecf1d-a43c-4764-911c-ef382b0d0c80/Textures/Terrain/Commonwealth/Commonwealth.4.-64.12_msn.DDS]
3. copying file from archive
4. ValidateSizeReader: expected 349680 bytes, got 191602
```

**Comment by Niedzwiedzw** [comment]
https://github.com/Niedzwiedzw/hoolamike/blob/d3eec9b5d5c0e2b5d1eb04cec007aab2181087f0/crates/hoolamike/src/compression/bethesda_archive.rs#L56

this is how I handle it

**Comment by Ryan-rsm-McKenzie** [comment]
Your branch conditions for decompressed files are backwards. You're decompressing decompressed files and not decompressing compressed files.

**Comment by Niedzwiedzw** [comment]
```rust
2. when extracting from [/home/niedzwiedz/Games/modding/hoolamike/playground/downloads/Data_Fallout4 - Textures6.ba2] to [./TEMP_BSA_FILES/db68f72d-e475-4875-9347-4c42cf827978/Textures/SetDressing/AudioEquipment/Speaker01Clean_s.DDS]
3. copying file from archive
4. ValidateSizeReader: expected 349680 bytes, got 349552
```


yup that did it. the mismatch is there for other entries so I guess it's just the modlist file that's broken :D

**Comment by Ryan-rsm-McKenzie** [comment]
The size mismatch is because you are only extracting the chunks, and are missing the dds header. You are probably looking for [`ba2::fo4::File::write`](https://docs.rs/ba2/latest/ba2/fo4/struct.File.html#method.write) instead.

**Comment by Niedzwiedzw** [comment]
thank you, im super new to modding and know nothing about it... all this i wrote so far is based on guesswork. so yeah thank you, you have probably just saved this project from being abandoned xd

**Comment by Niedzwiedzw** [comment]
@Ryan-rsm-McKenzie  could you please take a look at this? https://github.com/Niedzwiedzw/hoolamike/blob/51fb5c4ca53c541bf184b3dc245dd5c378edcd72/crates/hoolamike/src/compression/bethesda_archive.rs#L79

cause now it always writes 0 (I'm validating with a progress bar)
EDIT:
it's my bad, turns out I was not `.rewind()`-ing the file I was writing into, sorry for spam
