### ISSUE TITLE
external/DirectXTex/DirectXTex/DirectXTexDDS.cpp:950: HRESULT DirectX::EncodeDDSHeader(const TexMetadata&, DDS_FLAGS, void*, size_t, size_t&): Assertion `(metadata.arraySize % 6) == 0' failed.

### ISSUE THREAD

**Issue by Niedzwiedzw** [Ryan-rsm-McKenzie/bsa-rs#3]
`external/DirectXTex/DirectXTex/DirectXTexDDS.cpp:950: HRESULT DirectX::EncodeDDSHeader(const TexMetadata&, DDS_FLAGS, void*, size_t, size_t&): Assertion `(metadata.arraySize % 6) == 0' failed.`

this happens when extracting  a texture out of an archive... I'm also getting hash mismatches (according to the modlist file) for other BSA-extracted files, while size is correct

**Comment by Niedzwiedzw** [comment]
https://github.com/Niedzwiedzw/hoolamike/blob/ba2-archives-wip/crates%2Fhoolamike%2Fsrc%2Fcompression%2Fbethesda_archive.rs#L82

 here's all the code related do bethesda archives

**Comment by Ryan-rsm-McKenzie** [comment]
What file from what archive is this?

**Comment by Ryan-rsm-McKenzie** [comment]
Pull the latest commit and see if that helps. DDS files are implemented on a best effort basis, I couldn't even tell you what a cubemap is.

**Comment by Niedzwiedzw** [comment]
well I can't figure out what panics because I cannot catch it even with catch_unwind(), I'd be happy to contribute some kind of validation so that it returns and Error at least instead of hard panicking if you're interested.

as for the latest commit - the hashes are still invalid for some dds-es while the size is correct. I asked wabbajack guys and they say hashes must match 100% and there is no error in the modlist file.  so yeah here's the error
```rust
1. directive with hash [EZckcAeyfvI=] failed, provide it in support ticket
2. when handling directive: FromArchive(
    FromArchiveDirective {
        hash: "mtb4i+WoW70=",
        size: 524408,
        to: MaybeWindowsPath(
            "TEMP_BSA_FILES\\3efd7700-6d41-4fe4-987b-579cd527c85a\\Textures\\Shared\\Cubemaps\\mipblur_DefaultOutside1_bronze.dds",
        ),
        archive_hash_path: ArchiveHashAndPath(
            (
                "D4p7/Fon2zw=",
                MaybeWindowsPath(
                    "Textures\\Shared\\Cubemaps\\mipblur_DefaultOutside1_bronze.dds",
                ),
            ),
        ),
    },
)
3. when extracting from [/home/niedzwiedz/Games/modding/hoolamike/playground/downloads/Data_Fallout4 - Textures2.ba2] to [./TEMP_BSA_FILES/3efd7700-6d41-4fe4-987b-579cd527c85a/Textures/Shared/Cubemaps/mipblur_DefaultOutside1_bronze.dds]
4. copying file from archive
5. ValidateHashReader: expected mtb4i+WoW70=, got +dh2ux2EC8c=
```

**Comment by Niedzwiedzw** [comment]
the names are a bit mangled because I'm reading them from the modlist - I'll sort this out later. but essentially the file that's failing is vanilla game's `Data/Fallout4 - Textures2.ba2`

**Comment by Niedzwiedzw** [comment]
would you be interested in adding an integration  test that takes game directory from env var and tries unpacking all the files from all the .ba2 files found within that directory? shouldn't be too hard and I can do that

**Comment by Niedzwiedzw** [comment]
or maybe a simple cli would be more practical. whatever you decide I'm happy to help with that

**Comment by Ryan-rsm-McKenzie** [comment]
This library comes with it's own comprehensive test suite, and it flagged this assertion when I ran it. Something about the tool chain must have changed recently to enable the assertion, because it wasn't flagging when I wrote the tests.

As for the difference in hashes, it is probably because wabbajack is including the DDS headers in the file hash, which are very much a matter of opinion when it comes to writing them correctly. I think it's an error for wabbajack to include it, but if you really want the hashes to match, then you'll need to copy wabbajacks code for writing the headers yourself.

**Comment by Niedzwiedzw** [comment]
all right makes sense. I have zero knowledge about the workings of this, I'll only validate sizes for the dds files in that case.

as for the assertion failing - can I help with that in any way?

**Comment by Ryan-rsm-McKenzie** [comment]
Presumably, I just fixed the assertions

**Comment by Niedzwiedzw** [comment]
oooh yeah you're right, I assummed it's connected to the hash mismatch. now I've ran it again and yeah it's fixed - thank you very much!

**Comment by Niedzwiedzw** [comment]
so I've updated the modlist ant this happened again

external/DirectXTex/DirectXTex/DirectXTexDDS.cpp:961: HRESULT DirectX::EncodeDDSHeader(const TexMetadata&, DDS_FLAGS, uint8_t*, size_t, size_t&): Assertion `(metadata.arraySize % 6) == 0' failed.

**Comment by Ryan-rsm-McKenzie** [comment]
Are you sure you're using the latest release?

**Comment by Niedzwiedzw** [comment]
uhh I made a mistake when merging... I'm so sorry, I hope I didn't waste too much of your time!
