### ISSUE TITLE
[Feature request] open archives using memory mapped files

### ISSUE THREAD

**Issue by Niedzwiedzw** [Ryan-rsm-McKenzie/bsa-rs#4]
I have only briefly looked into internals of this library, but I noticed that in tests `File`s are created by memory mapping some fixtures from disk. would it be possible to open entire archive like this? cause if I'm correct reading an archive from path loads the entire file into memory. It would greatly decrease disk operations cause most of the time only one file is extracted from a BSA archive at a time.
if you're interested in adding such a feature I'd be happy to give it a go - if it makes sense at all of course

**Comment by Ryan-rsm-McKenzie** [comment]
Archives read from a path are memory mapped

**Comment by Niedzwiedzw** [comment]
oh
