### ISSUE TITLE
Creating ArchiveKey from raw hashes

### ISSUE THREAD

**Issue by Niedzwiedzw** [Ryan-rsm-McKenzie/bsa-rs#6]
in the manifest the key is serialized as directory hash and file hash, I wonder if this is somehow exposed in the library api

**Comment by Ryan-rsm-McKenzie** [comment]
You can construct hashes using the [`From`](https://docs.rs/ba2/latest/ba2/fo4/struct.ArchiveKey.html#impl-From%3CT%3E-for-Key%3C'static%3E) trait. That hash can then be used as key into the archive/directory. For example:
```rust
let key: ArchiveKey = b"Interface/HUDMenu.swf".into();
let file = archive.get(&key)?;
```
Lookinging up files using the embedded file strings is an anti pattern. The embedded file name is not guaranteed to be the one that generated the hash, and not all archives have file strings. It's also much faster to look files up using the hash.

**Comment by Ryan-rsm-McKenzie** [comment]
If you mean the manifest stores the raw numbers for the hash, then you can [build the hash directly](https://docs.rs/ba2/latest/ba2/fo4/struct.Hash.html) and use the `From` trait to construct the key.

**Comment by Niedzwiedzw** [comment]
> If you mean the manifest stores the raw numbers for the hash, then you can [build the hash directly](https://docs.rs/ba2/latest/ba2/fo4/struct.Hash.html) and use the `From` trait to construct the key.

hmmm I cannot find the From implementation


```rust
// ...
      .map(|extension| ba2::fo4::Hash {
          extension,
          file: name_hash,
          directory: dir_hash,
      })
      .map(ba2::fo4::ArchiveKey::from)
```

doesn't compile

**Comment by Niedzwiedzw** [comment]
ah, figured it out:
```
                                            .map(|key_hash| {
                                                key_hash
                                                    .conv::<ba2::fo4::FileHash>()
                                                    .conv::<ba2::fo4::ArchiveKey>()
                                            })

```

(conv() is .into() helper, with ergonomic generic parameter, comes from [amazing tap library](https://github.com/myrrlyn/tap))
